#!/usr/bin/env bash

set -euo pipefail

function check_build() {
    orc shell -c revng rm -rf share/revng/test/
    orc shell -c revng find -name "*.so" -delete
    orc shell -c revng ninja
    return 0
}

function drop_line() {
    FILE="$1"
    shift
    LINE="$1"
    shift
    test "$(grep "$LINE" "$FILE" | wc -l)" -eq 1
    grep -vF "$LINE" "$FILE" > "$FILE".new
    mv "$FILE".new "$FILE"
}

function drop_lib() {
    LIBRARY="$1"
    shift

    git rm -r lib/"$LIBRARY"
    drop_line lib/CMakeLists.txt 'add_subdirectory('"$LIBRARY"')'
    if test -d include/revng/"$LIBRARY"; then
        git rm -r include/revng/"$LIBRARY"
    fi
}

function drop_tu() {
    LIBRARY="$1"
    shift
    TU_NAME="$1"
    shift

    TU_PATH="lib/$LIBRARY/$TU_NAME.cpp"
    test -e "$TU_PATH"
    git rm "$TU_PATH"

    TU_HEADER="include/revng/$LIBRARY/$TU_NAME.h"
    if test -e "$TU_HEADER"; then
        git rm "$TU_HEADER";
    fi

    TU_HEADER="lib/$LIBRARY/$TU_NAME.h"
    if test -e "$TU_HEADER"; then
        git rm "$TU_HEADER";
    fi
}

# check_build
tag | sh

git commit --allow-empty -m'== Beginning of autogenerated commits for old backend removal =='

drop_lib LLMRename
git commit -a -m'[UNDO] Drop LLMRename'
# check_build

drop_lib ImportFromC
git rm share/revng/test/configuration/revng/import-from-c.yml
git rm -r share/revng/test/tests/analysis/ImportFromCAnalysis
git commit -a -m'[UNDO] Drop ImportFromC'
# check_build

drop_lib HeadersGeneration
drop_line 'lib/Pipebox/Pipebox.cpp' 'static RegisterContainer<CBytesContainer> C4;'
drop_line 'lib/Pipebox/Pipebox.cpp' 'static RegisterContainer<PTMLCTypeContainer> C6;'
drop_line 'lib/Pipebox/Pipebox.cpp' 'static RegisterSingleOutputPipe<ModelToHeader> P4;'
drop_line 'lib/Pipebox/Pipebox.cpp' 'static RegisterTypeDefinitionPipe<GenerateModelTypeDefinition> P5;'
drop_line 'lib/Pipebox/Pipebox.cpp' '#include "revng/HeadersGeneration/ModelToHeaderPipe.h"'
drop_line 'lib/Pipebox/Pipebox.cpp' '#include "revng/HeadersGeneration/ModelTypeDefinitionPipe.h"'
drop_line 'lib/Pipebox/CMakeLists.txt' revngModelToHeader

drop_lib Backend
git commit -a -m'Drop Backend and HeadersGeneration'
# check_build

git rm share/revng/test/configuration/revng/precedence-tests.yml
git rm -r ./share/revng/test/tests/c-operator-precedence
git rm ./tests/unit/llvm_lit_tests/OperatorPrecedenceResolutionPass.ll
git commit -a -m'Drop precedence-tests'
# check_build

git rm share/revng/test/configuration/revng/model-to-header.yml
git rm -r share/revng/test/tests/model-to-header
git commit -a -m'[UNDO] Drop model-to-header tests'

git rm ./tests/unit/llvm_lit_tests/TwosComplementArithmeticNormalization.ll

for TU in $(find lib/Canonicalize -name "*.cpp" | grep -vE 'HoistStructPhis.cpp|RemoveLLVMAssumeCallsPass.cpp|ExitSSAPass.cpp|SwitchToStatements.cpp|SimplifySwitchPass.cpp|LoopRewriteWithCanonicalIV.cpp|SplitOverflowIntrinsicsPass.cpp|RemoveConstantArrayReturnsPass.cpp|PeepholeOptimizationPass.cpp|TernaryReductionPass.cpp' | sed 's|.*/||; s/\.cpp//'); do
    drop_tu Canonicalize "$TU"
done

cat > lib/Canonicalize/CMakeLists.txt << 'EOF'
#
# This file is distributed under the MIT License. See LICENSE.md for details.
#

revng_add_analyses_library_internal(
  revngCanonicalize
  ExitSSAPass.cpp
  HoistStructPhis.cpp
  LoopRewriteWithCanonicalIV.cpp
  PeepholeOptimizationPass.cpp
  RemoveConstantArrayReturnsPass.cpp
  RemoveLLVMAssumeCallsPass.cpp
  SimplifySwitchPass.cpp
  SplitOverflowIntrinsicsPass.cpp
  SwitchToStatements.cpp
  TernaryReductionPass.cpp)

target_link_libraries(
  revngCanonicalize
  revngSupport
  revngABI
  revngLocalVariables
  revngModel
  revngPipes
  revngPTML
  revngLift
  ${LLVM_LIBRARIES})
EOF

git commit -a -m'Drop Canonicalize'
# check_build

drop_lib InitModelTypes
git commit -a -m'Drop InitModelTypes'
# check_build

drop_lib TypeNames
git commit -a -m'Drop TypeNames'
# check_build

for TU in $(git grep -c -E '#include.*(AST|Expr|BasicBlockNodeImpl|MetaRegion|RegionCFGTree)' lib/RestructureCFG | grep -F .cpp | sed 's/.cpp:.*//; s|lib/RestructureCFG/||'); do
    drop_tu RestructureCFG "$TU"
    drop_line lib/RestructureCFG/CMakeLists.txt "$TU.cpp"
done

set -x

sed 's|SelectScopePass.cpp|SelectScopePass.cpp)|' lib/RestructureCFG/CMakeLists.txt -i

git rm $(git grep -c -E '#include.*(AST|Expr|BasicBlockNodeImpl|MetaRegion|RegionCFGTree)' include/revng/RestructureCFG | grep -F .h | sed 's/:.*//')
git commit -a -m'Drop RestructureCFG'
check_build
